version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: nutrizulia_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nutrizulia_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nutrizulia_net

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: barbershop_backend
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nutrizulia_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_SECURITY_USER_NAME: admin
      SPRING_SECURITY_USER_PASSWORD: 1234
      JWT_SECRET: dW4tc2VjcmV0by1tdXktbGFyZ28teS1kaWZpY2lsLWRlLWFkaXZpbmFyLW51dHJpenVsaWE=
      JWT_EXPIRATION: 3600000
      CORS_ALLOWED_ORIGINS: http://localhost:4200,https://nutrizulia-backend.onrender.com/
      CORS_ALLOWED_METHODS: GET,POST,PUT,DELETE
      CORS_ALLOWED_HEADERS: "*"
      SERVER_PORT: 8080
    ports:
      - "8080:8080"
    networks:
      - nutrizulia_net

volumes:
  postgres_data:

networks:
  nutrizulia_net:
